1165 email users on document create for a schema
GCRC/nunaliit pull request #1176
Opened 2023-08-14 21:36 UTC by kunwarj

2023-08-15 15:21 UTC, alexgao1 requested changes
Notes so far: Seems to only email vetters, doesn't seem to email atlas adminstrators.
I think that despite the fact that it would email twice, when the submission server is on, it should send a "document was created for the schema" email plus the typical "a submission was made" email.

2023-08-15 15:21 UTC, alexgao1 commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/DocumentCreatedGenerator.java
> +        pw.println("<p>A new document has been created for schema: "+schemaName+".</p>");
Formatting

2023-08-15 15:21 UTC, alexgao1 commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/SubmissionMailNotifierImpl.java
> +            logger.info("Document created notification not sent because there are no recipients");
Formatting

2023-08-15 15:21 UTC, alexgao1 commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/SubmissionMailNotifierImpl.java
> +		logger.info("Sending documnet created mail notification for "
Typo

2023-08-15 15:29 UTC, alexgao1 commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/SubmissionMailNotifierImpl.java
> +		roles.add(atlasName+"administrator"); // atlas administrator
Typo, missing "_"

2023-08-15 15:31 UTC, alexgao1 commented
It should also log that an email cannot send if there is no mail server

2023-08-16 14:04 UTC, alexgao1 requested changes

2023-08-16 14:04 UTC, alexgao1 commented on nunaliit2-mail/src/main/java/ca/carleton/gcrc/mail/MailDeliveryImpl.java
> +		String userName = mailProperties.getProperty("mail."+prot+".user",null);
Unsure if mail. ... .user and .password are used as a part of mail configuration normally

2023-08-16 15:44 UTC, alexgao1 commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/SubmissionMailNotifierImpl.java
> +			logger.info("Email server is not cofigured to send document created notification");
typo

2023-08-16 15:52 UTC, kunwarj commented on nunaliit2-couch-submission/src/main/java/ca/carleton/gcrc/couch/submission/mail/SubmissionMailNotifierImpl.java
> +		Set<String> userIds = new HashSet<>();
Set and HasSet are being used here to create a unique set of userId's

2023-08-18 14:08 UTC, alexgao1 approved these changes

2023-08-18 14:17 UTC, merged